#-------------------------------
# General Site Settings

menu:

- {name: 'À propos',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Promis',   url: 'proj-1'}
- {name: 'Elektra',   url: 'proj-2'}
- {name: 'Générique',   url: 'proj-3'}
- {name: 'Scène',  url: 'proj-4'}
- {name: 'La Sphère',  url: 'proj-5'}



#-------------------------------
# Contact Section

social:


- {icon: 'github',    link: 'https://github.com/jolyannedesgardins'}
- {icon: 'https://www.linkedin.com/in/jolyanne-desjardins-ba95b9293?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app'}
- {icon: 'envelope',  link: 'mailto:mailto:l.nguyen.jolyannedesjardins9@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
